export interface DatabaseEngine {}
export interface StorageEngine {}
export interface CollectionManager {}
export interface PageManager {}
export interface CacheManager {}
export interface IndexManager {}
export interface QueryEngine {}
export interface SyncManager {}
export interface MongoProtocolLayer {}
